# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temperature', models.FloatField(verbose_name='Temperature degrees Celsius')),
                ('air_humidity', models.FloatField()),
                ('soil_moisture_1', models.FloatField(verbose_name='Soil moisture coriander')),
                ('soil_moisture_2', models.FloatField(verbose_name='Soil moisture basil')),
                ('image', models.ImageField(upload_to='')),
                ('light_on', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_profile', models.CharField(default='Normal', max_length=140)),
                ('logging_active', models.BooleanField(default=True)),
                ('logging_interval', models.IntegerField(verbose_name='Logging interval (minutes)')),
                ('save_night_images', models.BooleanField()),
                ('start_light', models.TimeField()),
                ('end_light', models.TimeField()),
                ('soil_moisture_pump_level', models.FloatField()),
                ('watering_time', models.IntegerField(verbose_name='Watering time (seconds)')),
                ('watering_inactive_period', models.IntegerField(verbose_name='Watering inactive period (minutes)')),
            ],
        ),
    ]
