# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0002_auto_20171009_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_loop', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='setting',
            name='loop_interval',
            field=models.IntegerField(default=2, verbose_name='Loop interval (seconds)'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
