# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0003_auto_20171010_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatus',
            name='message',
            field=models.CharField(default='OK', max_length=140),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='ok',
            field=models.BooleanField(default=True),
        ),
    ]
