# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0004_auto_20171011_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='self_regulate',
            field=models.BooleanField(default=True),
        ),
    ]
