# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0006_remove_setting_settings_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatus',
            name='last_watering',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 12, 46, 40, 113315, tzinfo=utc)),
        ),
    ]
