# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0007_systemstatus_last_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatus',
            name='free_space',
            field=models.CharField(default='OK', max_length=30),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='image',
            field=models.ImageField(upload_to='camera'),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='last_watering',
            field=models.DateTimeField(),
        ),
    ]
