# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0008_auto_20171021_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='free_space',
            field=models.FloatField(default=1000),
        ),
    ]
